services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: rvg_4dof_dev
    build:
      dockerfile: devcontainer.dockerfile
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
